### ISSUE TITLE
Errors with Yakindu SCT 3.2.0

### ISSUE THREAD

**Issue by PeronistaUniversal** [wendehals/arduino_sct_tools#11]
Trying using the code generator with Yakindu SCT 3.2.0 returns this error:

Guice creation errors:

> 1) No implementation for org.yakindu.sct.generator.c.IncludeProvider was bound.
>   while locating org.yakindu.sct.generator.c.IncludeProvider
>     for field at org.yakindu.sct.generator.c.StatemachineHeader._includeProvider(Unknown Source)
>   while locating org.yakindu.sct.generator.cpp.StatemachineHeader
>     for field at org.yakindu.sct.arduino.generator.cpp.ArduinoCodeGenerator.statemachineHeaderContent(Unknown Source)
>   at org.yakindu.sct.arduino.generator.cpp.ArduinoCppCodeGeneratorModule.configure(ArduinoCppCodeGeneratorModule.java:36)
> 
> 1 error
> Guice creation errors:
> 
> 1) No implementation for org.yakindu.sct.generator.c.IncludeProvider was bound.
>   while locating org.yakindu.sct.generator.c.IncludeProvider
>     for field at org.yakindu.sct.generator.c.StatemachineHeader._includeProvider(Unknown Source)
>   while locating org.yakindu.sct.generator.cpp.StatemachineHeader
>     for field at org.yakindu.sct.arduino.generator.cpp.ArduinoCodeGenerator.statemachineHeaderContent(Unknown Source)
>   at org.yakindu.sct.arduino.generator.cpp.ArduinoCppCodeGeneratorModule.configure(ArduinoCppCodeGeneratorModule.java:36)
> 
> 1 error

**Comment by Zarten** [comment]
same problem here

**Comment by Bukethead** [comment]
I'm having this problem as well.

**Comment by wendehals** [comment]
Problem fixed with release 0.8.0 and YAKINDU SCT 3.3.2
