### ISSUE TITLE
ATmega_Timer2.h missing when compiling projects

### ISSUE THREAD

**Issue by leventeBajczi** [wendehals/arduino_sct_tools#13]
With the most recent version of every component (Yakindu SCT, arduino-sct-tools and arduino-AVR (1.6.21)) there is an error message `../../src-gen/ArduinoMain.cpp:4:27: fatal error: ATmega_Timer2.h: No such file or directory`. I have tried with all the timer sources available, but to no avail. They are all missing.
Note: This June I could use the software flawlessly. I suspect there might be an update of one of the components that broke this software.

I have tried with my own project, and also with the included Blink example project. Both fail at the very same line.

**Comment by wendehals** [comment]
It may have been an incompatibility with the newest YAKINDU Statechart Tools version. The newest release has been tested against YAKINDU Statechart Tool 3.4.3 and works fine.
