### ISSUE TITLE
Error Generating Code Artifacts, Blink example

### ISSUE THREAD

**Issue by sefa1997** [wendehals/arduino_sct_tools#18]
I followed the steps like in the instrction.
As soon as I click on Generate Code Artifacts I get following error:

An internal error occurred during: "Execute SCT Genmodel Blink1.sgen".
Lorg/yakindu/sct/generator/cpp/Types;

**Comment by lehoangnam040** [comment]
Got this error, too

**Comment by pixelview95** [comment]
I had the exact same error even after multiple re installs. Any help would be appreciated.

**Comment by wendehals** [comment]
Fixed with release 0.10.0
