### ISSUE TITLE
The installation link https://wendehals.github.io/arduino_sct_tools/releases/ returns HTTP 404

### ISSUE THREAD

**Issue by mharizanov** [wendehals/arduino_sct_tools#8]
The installation link https://wendehals.github.io/arduino_sct_tools/releases/ returns HTTP 404

**Comment by Leative** [comment]
Be advised that this link leads to an eclipse update site which is not intended to be viewed in a browser. Apart from being slow, the link works for me inside eclipse. Check the "Installation Guide" in the readme of the repository for more information on how to use the link.

**Comment by wendehals** [comment]
The link works also for me. As Leative said, it's an eclipse update site.
